"""Supervised Persian sentiment fine-tuning using manually verified labels.

Usage:
  pip install -r requirements-training.txt
  python hooshFineTune.py --data labeled_comments.jsonl

Input JSONL format: one JSON object per line, with "text" and "label" (0=negative, 1=positive).
The old fine_tuned_data.json is NOT trustworthy supervised data because its labels
were generated by the model itself and the samples are duplicated.
"""
import argparse
import inspect
import json
import os
import random
from pathlib import Path

BASE_MODEL = "HooshvareLab/bert-fa-base-uncased-sentiment-deepsentipers-binary"


def read_gold_data(path: Path):
    if not path.is_file():
        raise ValueError("Manually labeled JSONL file not found: " + str(path))
    records = []
    seen = set()
    with path.open(encoding="utf-8") as handle:
        for lineno, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(f"Invalid JSON at line {lineno}") from error
            if not isinstance(item, dict):
                raise ValueError(f"Line {lineno} is not an object")
            text = item.get("text")
            label = item.get("label")
            if not isinstance(text, str) or not text.strip() or len(text) > 12000:
                raise ValueError(f"Line {lineno} must contain non-empty text <= 12000 chars")
            if type(label) is not int or label not in (0, 1):
                raise ValueError(f"Line {lineno} must have label 0 or 1")
            normalized = " ".join(text.split())
            if normalized in seen:
                raise ValueError(f"Duplicate text at line {lineno}; remove duplicates before training")
            seen.add(normalized)
            records.append({"text": normalized, "label": label})
    positives = sum(x["label"] == 1 for x in records)
    negatives = len(records) - positives
    if len(records) < 50 or min(positives, negatives) < 10:
        raise ValueError("Need at least 50 unique human-labelled texts and 10 per class; more is strongly recommended")
    return records


def stratified_split(records, seed=42):
    randomizer = random.Random(seed)
    groups = {0: [], 1: []}
    for record in records:
        groups[record["label"]].append(record)
    train, validation = [], []
    for items in groups.values():
        randomizer.shuffle(items)
        n_validation = max(2, round(len(items) * 0.20))
        validation.extend(items[:n_validation])
        train.extend(items[n_validation:])
    randomizer.shuffle(train)
    randomizer.shuffle(validation)
    return train, validation


def metrics(predictions):
    import numpy as np

    labels = predictions.label_ids
    logits = predictions.predictions
    if isinstance(logits, tuple):
        logits = logits[0]
    predicted = np.argmax(logits, axis=-1)
    accuracy = float(np.mean(predicted == labels))
    f1_scores = []
    for target in (0, 1):
        true_positives = int(np.sum((predicted == target) & (labels == target)))
        false_positives = int(np.sum((predicted == target) & (labels != target)))
        false_negatives = int(np.sum((predicted != target) & (labels == target)))
        denominator = 2 * true_positives + false_positives + false_negatives
        f1_scores.append(2 * true_positives / denominator if denominator else 0.0)
    return {"accuracy": accuracy, "macro_f1": sum(f1_scores) / 2}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=Path, required=True, help="JSONL with manually verified labels")
    parser.add_argument("--output", type=Path, default=Path("fine_tuned_model"))
    args = parser.parse_args()

    records = read_gold_data(args.data)
    from datasets import Dataset
    from transformers import (
        AutoModelForSequenceClassification,
        AutoTokenizer,
        DataCollatorWithPadding,
        Trainer,
        TrainingArguments,
    )
    train_rows, validation_rows = stratified_split(records)
    print(f"Training on {len(train_rows)} records, evaluating on {len(validation_rows)} held-out records")
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
    model = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL)

    def tokenize(batch):
        result = tokenizer(batch["text"], truncation=True, max_length=512)
        return result

    train_set = Dataset.from_list(train_rows).map(tokenize, batched=True)
    validation_set = Dataset.from_list(validation_rows).map(tokenize, batched=True)

    kwargs = dict(
        output_dir="./results", num_train_epochs=3,
        per_device_train_batch_size=8, per_device_eval_batch_size=8,
        weight_decay=0.01, save_strategy="no",
        logging_steps=10, report_to="none",
    )
    strategy_name = "eval_strategy" if "eval_strategy" in inspect.signature(TrainingArguments).parameters else "evaluation_strategy"
    kwargs[strategy_name] = "epoch"
    settings = TrainingArguments(**kwargs)
    trainer = Trainer(
        model=model, args=settings,
        train_dataset=train_set, eval_dataset=validation_set,
        data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
        compute_metrics=metrics,
    )
    trainer.train()
    print("Held-out evaluation:", trainer.evaluate())
    os.makedirs(args.output, exist_ok=True)
    model.save_pretrained(str(args.output))
    tokenizer.save_pretrained(str(args.output))
    print("Model saved:", args.output)


if __name__ == "__main__":
    main()
